version: '3.8'

services:
  ros2_webots_node:
    build: .
    container_name: webots_ros2_final
    
    # RViz2 구동 시 공유 메모리 충돌 방지
    shm_size: '1gb'
    
    extra_hosts:
      - "host.docker.internal:host-gateway"
    
    volumes:
      - ./src:/ros2_ws/src
    
    environment:
      # X11 디스플레이를 윈도우(호스트)의 0번 모니터로 전송
      - DISPLAY=host.docker.internal:0
      - WEBOTS_CONTROLLER_URL=tcp://host.docker.internal:1234
      - QT_X11_NO_MITSHM=1
    
    # VNC 스크립트 대신 컨테이너 유지 명령어로 복구
    command: tail -f /dev/null
    tty: true
    stdin_open: true