FROM osrf/ros:humble-desktop

ENV DEBIAN_FRONTEND=noninteractive
ENV LANG=en_US.UTF-8
ENV LC_ALL=en_US.UTF-8

# Locale
RUN apt-get update && apt-get install -y locales && \
    locale-gen en_US en_US.UTF-8 && \
    update-locale LANG=en_US.UTF-8 LC_ALL=en_US.UTF-8

# 기본 패키지 + GUI/VNC
RUN apt-get update && apt-get install -y \
    curl gnupg2 lsb-release \
    net-tools iputils-ping netcat \
    git software-properties-common wget \
    python3-colcon-common-extensions \
    mesa-utils \
    xvfb \
    x11vnc \
    novnc \
    websockify \
    fluxbox \
    xterm \
    libgl1-mesa-glx \
    libglu1-mesa \
    libgl1-mesa-dri \
    libx11-6 \
    libxext6 \
    libqt5gui5 \
    libqt5x11extras5 \
    libxcb-xinerama0 \
    libxcb-randr0 \
    libxcb-render-util0 \
    libxcb-shape0 \
    libxcb-xfixes0 \
    libxcb-sync1 \
    libxcb-icccm4 \
    libxcb-image0 \
    libxcb-keysyms1 \
    && rm -rf /var/lib/apt/lists/*

# ROS 패키지
RUN apt-get update && apt-get install -y \
    ros-humble-webots-ros2 ros-humble-ros2-control ros-humble-ros2-controllers \
    ros-humble-nav2-msgs ros-humble-nav2-costmap-2d ros-humble-navigation2 ros-humble-nav2-bringup \
    ros-humble-tf2-sensor-msgs ros-humble-tf2-geometry-msgs ros-humble-tf2-eigen \
    ros-humble-octomap ros-humble-octomap-msgs ros-humble-octomap-mapping \
    ros-humble-visualization-msgs ros-humble-pcl-conversions ros-humble-pcl-ros ros-humble-pointcloud-to-laserscan \
    ros-humble-rosgraph-msgs ros-humble-cv-bridge ros-humble-image-transport ros-humble-rmw-cyclonedds-cpp \
    python3-colcon-common-extensions \
    && rm -rf /var/lib/apt/lists/*

RUN apt update && apt install -y python3-pip

# Webots 설치
RUN wget -q https://github.com/cyberbotics/webots/releases/download/R2025a/webots_2025a_amd64.deb && \
    apt-get update && apt-get install -y ./webots_2025a_amd64.deb && \
    rm webots_2025a_amd64.deb

ENV WEBOTS_HOME=/usr/local/webots
ENV PYTHONPATH=$WEBOTS_HOME/lib/controller/python:$PYTHONPATH
ENV LD_LIBRARY_PATH=$WEBOTS_HOME/lib/controller:$LD_LIBRARY_PATH

# GTSAM
RUN add-apt-repository ppa:borglab/gtsam-release-4.1 -y && \
    apt-get update && \
    apt-get install -y libgtsam-dev libgtsam-unstable-dev && \
    rm -rf /var/lib/apt/lists/*

WORKDIR /ros2_ws

RUN echo "source /opt/ros/humble/setup.bash" >> /root/.bashrc
RUN echo "source  /ros2_ws/install/setup.bash" >> ~/.bashrc
#RUN echo "export RMW_IMPLEMENTATION=rmw_cyclonedds_cpp" >> ~/.bashrc

# Mac에서는 X11 forwarding 대신 가상 디스플레이 사용
ENV DISPLAY=:1
ENV LIBGL_ALWAYS_SOFTWARE=1
ENV QT_X11_NO_MITSHM=1

# 6. 환경 설정
WORKDIR /ros2_ws
# 호스트의 소스 코드를 도커 안으로 복사
COPY src /ros2_ws/src
# 🌟 [핵심] 이미지를 구울 때 colcon build를 아예 끝내버립니다!
RUN /bin/bash -c '. /opt/ros/humble/setup.bash && colcon build --symlink-install'
RUN echo "source /opt/ros/humble/setup.bash" >> ~/.bashrc
RUN echo "source  /ros2_ws/install/setup.bash" >> ~/.bashrc
# RUN echo "export RMW_IMPLEMENTATION=rmw_cyclonedds_cpp" >> ~/.bashrc
ENV USER=root

# 🌟 7. VNC 무한 대기 시작 스크립트 작성 (자물쇠 청소 기능 추가)
RUN echo '#!/bin/bash\n\
export DISPLAY=:0\n\
# 👇 바로 이 부분! 재시작 시 꼬이는 이전 가상 모니터 찌꺼기를 강제로 박살냅니다.\n\
rm -rf /tmp/.X*\n\
Xvfb :0 -screen 0 1920x1080x24 &\n\
sleep 2\n\
fluxbox &\n\
x11vnc -display :0 -forever -nopw -bg -xkb &\n\
websockify --web=/usr/share/novnc/ 6080 localhost:5900 &\n\
echo "====================================================="\n\
echo "🚀 VNC 서버 부팅 완료!"\n\
echo "🌐 맥북 사파리/크롬에서 http://localhost:6080 접속하세요!"\n\
echo "====================================================="\n\
exec bash' > /start_vnc.sh && chmod +x /start_vnc.sh

EXPOSE 5900 6080